In [1]:
import pandas as pd

In [3]:
all_inven = pd.read_csv("rentals/All/rentalInventory_All.csv")
OneBd = pd.read_csv("rentals/OneBd/rentalInventory_OneBd.csv")
Studio = pd.read_csv("rentals/Studio/rentalInventory_Studio.csv")
ThreePlusBd = pd.read_csv("rentals/ThreePlusBd/rentalInventory_ThreePlusBd.csv")
TwoBd = pd.read_csv("rentals/TwoBd/rentalInventory_TwoBd.csv")

all_inven = all_inven[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'All'})
OneBd = OneBd[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'OneBd'})
Studio = Studio[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'Studio'})
ThreePlusBd = ThreePlusBd[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'ThreePlusBd'})
TwoBd = TwoBd[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'TwoBd'})

inventory = pd.merge(all_inven,OneBd,on = ['areaName','Borough','areaType'])
inventory = pd.merge(inventory,Studio,on = ['areaName','Borough','areaType'])
inventory = pd.merge(inventory,TwoBd,on = ['areaName','Borough','areaType'])
inventory = pd.merge(inventory,ThreePlusBd,on = ['areaName','Borough','areaType'])
inventory

,areaName,Borough,areaType,All,OneBd,Studio,TwoBd,ThreePlusBd
0,All Downtown,Manhattan,submarket,5877,2134.0,1287.0,1613.0,843.0
1,All Midtown,Manhattan,submarket,4725,1889.0,1067.0,1282.0,487.0
2,All Upper East Side,Manhattan,submarket,3006,1215.0,629.0,797.0,365.0
3,All Upper Manhattan,Manhattan,submarket,3268,1044.0,285.0,1087.0,852.0
4,All Upper West Side,Manhattan,submarket,2636,1062.0,504.0,644.0,426.0
5,Alley Park,Queens,neighborhood,0,NaN,NaN,NaN,NaN
6,Astoria,Queens,neighborhood,1903,802.0,106.0,720.0,275.0
7,Auburndale,Queens,neighborhood,20,9.0,1.0,8.0,2.0
8,Bath Beach,Brooklyn,neighborhood,67,24.0,1.0,25.0,17.0
9,Battery Park City,Manhattan,neighborhood,213,82.0,29.0,71.0,31.0
10,Bay Ridge,Brooklyn,neighborhood,601,196.0,57.0,227.0,121.0
11,Baychester,Bronx,neighborhood,0,NaN,NaN,NaN,NaN
12,Bayside,Queens,neighborhood,27,6.0,4.0,8.0,9.0
13,Bedford Park,Bronx,neighborhood,14,4.0,1.0,3.0,6.0
14,Bedford-Stuyvesant,Brooklyn,neighborhood,2325,544.0,92.0,869.0,820.0
15,Bellerose,Queens,neighborhood,2,NaN,NaN,NaN,2.0
16,Belmont,Bronx,neighborhood,35,5.0,NaN,11.0,19.0
17,Bensonhurst,Brooklyn,neighborhood,121,51.0,7.0,31.0,32.0
18,Bergen Beach,Brooklyn,neighborhood,14,3.0,NaN,5.0,6.0
19,Boerum Hill,Brooklyn,neighborhood,113,43.0,5.0,42.0,23.0
20,Borough Park,Brooklyn,neighborhood,84,28.0,8.0,35.0,13.0
21,Bowne Park,Queens,neighborhood,0,NaN,NaN,NaN,NaN
22,Briarwood,Queens,neighborhood,71,36.0,6.0,25.0,4.0
23,Brighton Beach,Brooklyn,neighborhood,73,36.0,4.0,24.0,9.0
24,Bronx,Bronx,borough,1154,404.0,91.0,367.0,292.0
25,Bronxwood,Bronx,neighborhood,17,13.0,NaN,4.0,NaN
26,Brooklyn,Brooklyn,borough,17556,5022.0,1277.0,6381.0,4876.0
27,Brooklyn Heights,Brooklyn,neighborhood,207,66.0,55.0,55.0,31.0
28,Brookville,Queens,neighborhood,1,NaN,NaN,NaN,1.0
29,Brownsville,Brooklyn,neighborhood,50,11.0,2.0,16.0,21.0
...,...,...,...,...,...,...,...,...
172,South Queens,Queens,submarket,157,41.0,29.0,45.0,42.0
173,South Richmond Hill,Queens,neighborhood,3,NaN,1.0,NaN,2.0
174,Springfield Gardens,Queens,neighborhood,5,1.0,NaN,4.0,NaN
175,St. Albans,Queens,neighborhood,5,2.0,NaN,1.0,2.0
176,Staten Island,Staten Island,borough,97,36.0,11.0,25.0,25.0
177,Stuyvesant Town/PCV,Manhattan,neighborhood,101,20.0,NaN,45.0,36.0
178,Sunnyside,Queens,neighborhood,309,172.0,31.0,90.0,16.0
179,Sunset Park,Brooklyn,neighborhood,225,61.0,9.0,104.0,51.0
180,The Rockaways,Queens,submarket,89,30.0,13.0,23.0,23.0
181,Throgs Neck,Bronx,neighborhood,15,3.0,1.0,4.0,7.0
182,Tremont,Bronx,neighborhood,36,7.0,5.0,12.0,12.0
183,Tribeca,Manhattan,neighborhood,296,86.0,41.0,87.0,82.0
184,University Heights,Bronx,neighborhood,41,17.0,3.0,15.0,6.0
185,Upper East Side,Manhattan,neighborhood,3006,1215.0,629.0,797.0,365.0
186,Upper West Side,Manhattan,neighborhood,2636,1062.0,504.0,644.0,426.0
187,Utopia,Queens,neighborhood,3,NaN,NaN,NaN,3.0
188,Van Nest,Bronx,neighborhood,8,6.0,1.0,NaN,1.0
189,Wakefield,Bronx,neighborhood,13,5.0,NaN,1.0,7.0
190,Washington Heights,Manhattan,neighborhood,896,257.0,68.0,318.0,253.0
191,West Harlem,Manhattan,neighborhood,81,16.0,1.0,27.0,37.0
192,West Village,Manhattan,neighborhood,532,222.0,143.0,118.0,49.0
193,Westchester Village,Bronx,neighborhood,2,1.0,NaN,1.0,NaN
194,Whitestone,Queens,neighborhood,17,6.0,NaN,8.0,3.0
195,Williamsbridge,Bronx,neighborhood,20,5.0,1.0,6.0,8.0
196,Williamsburg,Brooklyn,neighborhood,3244,959.0,186.0,1295.0,804.0
197,Windsor Terrace,Brooklyn,neighborhood,118,35.0,5.0,59.0,19.0
198,Woodhaven,Queens,neighborhood,15,6.0,NaN,5.0,4.0
199,Woodlawn,Bronx,neighborhood,4,3.0,NaN,1.0,NaN
200,Woodside,Queens,neighborhood,125,68.0,13.0,24.0,20.0
201,Woodstock,Bronx,neighborhood,20,6.0,NaN,6.0,8.0

In [4]:
all_inven = pd.read_csv("rentals/All/medianAskingRent_All.csv")
OneBd = pd.read_csv("rentals/OneBd/medianAskingRent_OneBd.csv")
Studio = pd.read_csv("rentals/Studio/medianAskingRent_Studio.csv")
ThreePlusBd = pd.read_csv("rentals/ThreePlusBd/medianAskingRent_ThreePlusBd.csv")
TwoBd = pd.read_csv("rentals/TwoBd/medianAskingRent_TwoBd.csv")

all_inven = all_inven[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'All'})
OneBd = OneBd[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'OneBd'})
Studio = Studio[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'Studio'})
ThreePlusBd = ThreePlusBd[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'ThreePlusBd'})
TwoBd = TwoBd[['areaName','Borough','areaType','2018-10']].rename(columns = {'2018-10':'TwoBd'})

price = pd.merge(all_inven,OneBd,on = ['areaName','Borough','areaType'])
price = pd.merge(price,Studio,on = ['areaName','Borough','areaType'])
price = pd.merge(price,TwoBd,on = ['areaName','Borough','areaType'])
price = pd.merge(price,ThreePlusBd,on = ['areaName','Borough','areaType'])
price

,areaName,Borough,areaType,All,OneBd,Studio,TwoBd,ThreePlusBd
0,All Downtown,Manhattan,submarket,3850.0,3651.0,2815.0,4500.0,6060.0
1,All Midtown,Manhattan,submarket,3595.0,3550.0,2595.0,4800.0,5959.0
2,All Upper East Side,Manhattan,submarket,3000.0,2888.0,2150.0,3500.0,7895.0
3,All Upper Manhattan,Manhattan,submarket,2350.0,1950.0,1750.0,2400.0,3025.0
4,All Upper West Side,Manhattan,submarket,3400.0,3200.0,2250.0,4799.0,6998.0
5,Alley Park,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
6,Astoria,Queens,neighborhood,2200.0,1900.0,1750.0,2300.0,2800.0
7,Auburndale,Queens,neighborhood,1945.0,NaN,NaN,NaN,NaN
8,Bath Beach,Brooklyn,neighborhood,1750.0,1537.0,NaN,1799.0,2500.0
9,Battery Park City,Manhattan,neighborhood,4900.0,3773.0,3250.0,6450.0,12000.0
10,Bay Ridge,Brooklyn,neighborhood,1999.0,1699.0,1595.0,2150.0,2595.0
11,Baychester,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN
12,Bayside,Queens,neighborhood,2400.0,NaN,NaN,NaN,NaN
13,Bedford Park,Bronx,neighborhood,1823.0,NaN,NaN,NaN,NaN
14,Bedford-Stuyvesant,Brooklyn,neighborhood,2500.0,2195.0,1948.0,2500.0,2995.0
15,Bellerose,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
16,Belmont,Bronx,neighborhood,2100.0,NaN,NaN,1800.0,2200.0
17,Bensonhurst,Brooklyn,neighborhood,1850.0,1550.0,NaN,1899.0,2450.0
18,Bergen Beach,Brooklyn,neighborhood,2088.0,NaN,NaN,NaN,NaN
19,Boerum Hill,Brooklyn,neighborhood,3250.0,2600.0,NaN,3850.0,5800.0
20,Borough Park,Brooklyn,neighborhood,1900.0,1550.0,NaN,1900.0,2350.0
21,Bowne Park,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
22,Briarwood,Queens,neighborhood,1750.0,1649.0,NaN,1999.0,NaN
23,Brighton Beach,Brooklyn,neighborhood,2050.0,1750.0,NaN,2497.0,NaN
24,Bronx,Bronx,borough,1900.0,1600.0,1475.0,1995.0,2350.0
25,Bronxwood,Bronx,neighborhood,1625.0,1595.0,NaN,NaN,NaN
26,Brooklyn,Brooklyn,borough,2550.0,2250.0,2050.0,2500.0,3000.0
27,Brooklyn Heights,Brooklyn,neighborhood,3391.0,2998.0,2295.0,4500.0,7400.0
28,Brookville,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
29,Brownsville,Brooklyn,neighborhood,2025.0,1550.0,NaN,1850.0,2295.0
...,...,...,...,...,...,...,...,...
172,South Queens,Queens,submarket,2000.0,1700.0,1550.0,2100.0,2500.0
173,South Richmond Hill,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
174,Springfield Gardens,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
175,St. Albans,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
176,Staten Island,Staten Island,borough,1900.0,1463.0,1690.0,2000.0,2300.0
177,Stuyvesant Town/PCV,Manhattan,neighborhood,4052.0,3653.0,NaN,3867.0,4606.0
178,Sunnyside,Queens,neighborhood,1935.0,1850.0,1653.0,2325.0,2875.0
179,Sunset Park,Brooklyn,neighborhood,1995.0,1700.0,NaN,2000.0,2400.0
180,The Rockaways,Queens,submarket,1850.0,1600.0,1395.0,2100.0,2399.0
181,Throgs Neck,Bronx,neighborhood,2150.0,NaN,NaN,NaN,NaN
182,Tremont,Bronx,neighborhood,1823.0,NaN,NaN,1800.0,2152.0
183,Tribeca,Manhattan,neighborhood,6860.0,4900.0,4275.0,7950.0,15170.0
184,University Heights,Bronx,neighborhood,1695.0,1535.0,NaN,1750.0,NaN
185,Upper East Side,Manhattan,neighborhood,3000.0,2888.0,2150.0,3500.0,7895.0
186,Upper West Side,Manhattan,neighborhood,3400.0,3200.0,2250.0,4799.0,6998.0
187,Utopia,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN
188,Van Nest,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN
189,Wakefield,Bronx,neighborhood,2100.0,NaN,NaN,NaN,NaN
190,Washington Heights,Manhattan,neighborhood,2250.0,1845.0,1695.0,2295.0,2950.0
191,West Harlem,Manhattan,neighborhood,2550.0,2000.0,NaN,2300.0,2999.0
192,West Village,Manhattan,neighborhood,3900.0,3825.0,2895.0,4744.0,7995.0
193,Westchester Village,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN
194,Whitestone,Queens,neighborhood,2250.0,NaN,NaN,NaN,NaN
195,Williamsbridge,Bronx,neighborhood,1825.0,NaN,NaN,NaN,NaN
196,Williamsburg,Brooklyn,neighborhood,3000.0,2775.0,2500.0,3025.0,3599.0
197,Windsor Terrace,Brooklyn,neighborhood,2643.0,2200.0,NaN,2900.0,3195.0
198,Woodhaven,Queens,neighborhood,1850.0,NaN,NaN,NaN,NaN
199,Woodlawn,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN
200,Woodside,Queens,neighborhood,1850.0,1785.0,1595.0,2200.0,2625.0
201,Woodstock,Bronx,neighborhood,1950.0,NaN,NaN,NaN,NaN

In [6]:
OneBd = pd.read_csv("rentals/OneBd/medianAskingRent_OneBd.csv")

OneBd

,areaName,Borough,areaType,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,...,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10
0,All Downtown,Manhattan,submarket,2999.0,2975.0,2900.0,2982.0,2995.0,3000.0,3000.0,...,3500.0,3583.0,3575.0,3546.0,3500.0,3500.0,3500.0,3560.0,3600.0,3651.0
1,All Midtown,Manhattan,submarket,2800.0,2800.0,2850.0,2895.0,2900.0,2990.0,3000.0,...,3351.0,3387.0,3375.0,3395.0,3495.0,3500.0,3500.0,3500.0,3550.0,3550.0
2,All Upper East Side,Manhattan,submarket,2350.0,2300.0,2350.0,2470.0,2500.0,2500.0,2500.0,...,2800.0,2750.0,2775.0,2697.0,2695.0,2800.0,2795.0,2795.0,2795.0,2888.0
3,All Upper Manhattan,Manhattan,submarket,1500.0,1516.0,1545.0,1516.0,1550.0,1575.0,1550.0,...,1900.0,1950.0,1950.0,1995.0,2000.0,2000.0,1995.0,1957.0,1950.0,1950.0
4,All Upper West Side,Manhattan,submarket,2600.0,2550.0,2495.0,2500.0,2500.0,2600.0,2600.0,...,3100.0,3078.0,3095.0,3100.0,3100.0,3100.0,3050.0,3050.0,3150.0,3200.0
5,Alley Park,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Astoria,Queens,neighborhood,1395.0,1450.0,1450.0,1395.0,1400.0,1550.0,1475.0,...,1850.0,1850.0,1850.0,1873.0,1900.0,1850.0,1900.0,1900.0,1938.0,1900.0
7,Auburndale,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Bath Beach,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1500.0,NaN,NaN,NaN,1550.0,1625.0,1500.0,1500.0,1499.0,1537.0
9,Battery Park City,Manhattan,neighborhood,2875.0,2800.0,2900.0,2873.0,2800.0,2900.0,2950.0,...,3499.0,3475.0,3595.0,3575.0,3698.0,3650.0,3950.0,3950.0,3850.0,3773.0
10,Bay Ridge,Brooklyn,neighborhood,1350.0,1350.0,1350.0,1325.0,1300.0,1300.0,1300.0,...,1650.0,1675.0,1650.0,1675.0,1675.0,1700.0,1699.0,1700.0,1700.0,1699.0
11,Baychester,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Bayside,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1725.0,1650.0,NaN,1625.0,NaN,NaN,NaN,NaN,NaN
13,Bedford Park,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Bedford-Stuyvesant,Brooklyn,neighborhood,1600.0,1500.0,1350.0,1375.0,1400.0,1350.0,1300.0,...,2000.0,2000.0,2100.0,2100.0,2100.0,2149.0,2140.0,2197.0,2200.0,2195.0
15,Bellerose,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Belmont,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1575.0,NaN,NaN
17,Bensonhurst,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1573.0,1595.0,1505.0,1550.0,1650.0,1588.0,1550.0,1525.0,1575.0,1550.0
18,Bergen Beach,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Boerum Hill,Brooklyn,neighborhood,2000.0,1950.0,1975.0,2050.0,2050.0,2360.0,2355.0,...,2375.0,2500.0,2500.0,2600.0,2768.0,2700.0,2655.0,2800.0,2700.0,2600.0
20,Borough Park,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1590.0,1500.0,1598.0,1590.0,1550.0,1600.0,1620.0,1620.0,1550.0,1550.0
21,Bowne Park,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Briarwood,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1625.0,1695.0,1699.0,1695.0,1685.0,1700.0,1699.0,1600.0,1650.0,1649.0
23,Brighton Beach,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1719.0,1895.0,1825.0,1744.0,1875.0,1900.0,1900.0,1900.0,1750.0,1750.0
24,Bronx,Bronx,borough,1350.0,1400.0,1400.0,1375.0,1400.0,1300.0,1200.0,...,1550.0,1578.0,1550.0,1580.0,1578.0,1550.0,1575.0,1600.0,1625.0,1600.0
25,Bronxwood,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1600.0,1450.0,1450.0,NaN,1550.0,1550.0,1575.0,1550.0,1595.0
26,Brooklyn,Brooklyn,borough,1950.0,1938.0,1897.0,1941.0,2000.0,2000.0,2050.0,...,2200.0,2200.0,2200.0,2250.0,2250.0,2275.0,2300.0,2300.0,2300.0,2250.0
27,Brooklyn Heights,Brooklyn,neighborhood,2000.0,1950.0,1850.0,1863.0,2200.0,2200.0,2398.0,...,2870.0,2796.0,2800.0,2796.0,2900.0,2900.0,2800.0,3000.0,2784.0,2998.0
28,Brookville,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Brownsville,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1550.0,1599.0,NaN,1475.0,1475.0,1488.0,NaN,NaN,NaN,1550.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,South Queens,Queens,submarket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1600.0,1600.0,1700.0,1650.0,1650.0,1750.0,1797.0,1745.0,1689.0,1700.0
173,South Richmond Hill,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,Springfield Gardens,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,St. Albans,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,Staten Island,Staten Island,borough,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1600.0,1600.0,1600.0,1513.0,1500.0,1695.0,1995.0,1550.0,1879.0,1463.0
177,Stuyvesant Town/PCV,Manhattan,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3585.0,3623.0,3580.0,3655.0,3609.0,NaN,3549.0,3587.0,3635.0,3653.0
178,Sunnyside,Queens,neighborhood,1350.0,1350.0,1350.0,1399.0,1400.0,1375.0,1400.0,...,1875.0,1900.0,1900.0,1945.0,1900.0,1885.0,1850.0,1800.0,1850.0,1850.0
179,Sunset Park,Brooklyn,neighborhood,1200.0,1200.0,1175.0,1188.0,1200.0,NaN,NaN,...,1650.0,1650.0,1750.0,1747.0,1750.0,1700.0,1713.0,1700.0,1719.0,1700.0
180,The Rockaways,Queens,submarket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1585.0,NaN,NaN,1600.0,1599.0,1650.0,1600.0,1650.0,1600.0
181,Throgs Neck,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,Tremont,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1538.0,NaN,NaN
183,Tribeca,Manhattan,neighborhood,3960.0,4000.0,3900.0,3900.0,3825.0,3695.0,3695.0,...,4495.0,4500.0,4500.0,4673.0,4695.0,4625.0,4500.0,4598.0,4695.0,4900.0
184,University Heights,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1499.0,1500.0,1450.0,1450.0,1463.0,1450.0,NaN,NaN,NaN,1535.0
185,Upper East Side,Manhattan,neighborhood,2350.0,2300.0,2350.0,2470.0,2500.0,2500.0,2500.0,...,2800.0,2750.0,2775.0,2697.0,2695.0,2800.0,2795.0,2795.0,2795.0,2888.0
186,Upper West Side,Manhattan,neighborhood,2600.0,2550.0,2495.0,2500.0,2500.0,2600.0,2600.0,...,3100.0,3078.0,3095.0,3100.0,3100.0,3100.0,3050.0,3050.0,3150.0,3200.0
187,Utopia,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,Van Nest,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,Wakefield,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,Washington Heights,Manhattan,neighborhood,1400.0,1395.0,1395.0,1397.0,1355.0,1433.0,1495.0,...,1795.0,1798.0,1795.0,1795.0,1802.0,1850.0,1825.0,1818.0,1800.0,1845.0
191,West Harlem,Manhattan,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2725.0,2725.0,2300.0,2363.0,2348.0,2200.0,1950.0,1850.0,2000.0,2000.0
192,West Village,Manhattan,neighborhood,3298.0,3100.0,3000.0,3048.0,3000.0,3095.0,3288.0,...,3500.0,3750.0,3750.0,3750.0,3780.0,3798.0,3800.0,3923.0,3895.0,3825.0
193,Westchester Village,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,Whitestone,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,Williamsbridge,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,Williamsburg,Brooklyn,neighborhood,2383.0,2350.0,2304.0,2450.0,2450.0,2585.0,2558.0,...,2800.0,2800.0,2795.0,2800.0,2750.0,2756.0,2750.0,2750.0,2700.0,2775.0
197,Windsor Terrace,Brooklyn,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,1800.0,...,2200.0,2250.0,2198.0,2200.0,2225.0,2199.0,2200.0,2100.0,2138.0,2200.0
198,Woodhaven,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1625.0,1549.0,NaN,NaN,NaN,NaN,NaN
199,Woodlawn,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,Woodside,Queens,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1690.0,1700.0,1750.0,1790.0,1790.0,1790.0,1750.0,1763.0,1750.0,1785.0
201,Woodstock,Bronx,neighborhood,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
inventory = inventory[inventory['areaType']=='borough']
inventory

,areaName,Borough,areaType,All,OneBd,Studio,TwoBd,ThreePlusBd
24,Bronx,Bronx,borough,1154,404.0,91.0,367.0,292.0
26,Brooklyn,Brooklyn,borough,17556,5022.0,1277.0,6381.0,4876.0
110,Manhattan,Manhattan,borough,19604,7369.0,3788.0,5444.0,3003.0
153,Queens,Queens,borough,5581,2190.0,603.0,1822.0,966.0
176,Staten Island,Staten Island,borough,97,36.0,11.0,25.0,25.0

In [132]:
price = price[price['areaType']=='borough']
price

,areaName,Borough,areaType,All,OneBd,Studio,TwoBd,ThreePlusBd
24,Bronx,Bronx,borough,1900.0,1600.0,1475.0,1995.0,2350.0
26,Brooklyn,Brooklyn,borough,2550.0,2250.0,2050.0,2500.0,3000.0
110,Manhattan,Manhattan,borough,3300.0,3200.0,2450.0,3825.0,4999.0
153,Queens,Queens,borough,2200.0,1900.0,1700.0,2300.0,2795.0
176,Staten Island,Staten Island,borough,1900.0,1463.0,1690.0,2000.0,2300.0

In [7]:
listings = pd.read_csv("listings.csv")

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
for i in listings.columns:
    print(i,'|||',listings[i][0])

id ||| 3647
listing_url ||| https://www.airbnb.com/rooms/3647
scrape_id ||| 20190912153101
last_scraped ||| 2019-09-13
name ||| THE VILLAGE OF HARLEM....NEW YORK !
summary ||| nan
space ||| WELCOME TO OUR INTERNATIONAL URBAN COMMUNITY This Spacious 1 bedroom  is with Plenty of Windows with a View....... Sleeps.....Four Adults.....two in the Livingrm. with (2) Sofa-beds.  (Website hidden by Airbnb) two in the Bedrm.on a very Comfortable Queen Size Bed... A Complete Bathrm.....With Shower and Bathtub....... Fully Equipped with Linens & Towels........ Spacious Living Room......Flat ScreenTelevision.....DVD Player with Movies available for your viewing during your stay............................................................................. Dining Area.....for Morning Coffee or Tea..................................................... The Kitchen Area is Modern with Granite Counter Top... includes the use of a Coffee Maker...Microwave to Heat up a Carry Out/In Meal.... Not suited for a Gourmet Cook...or Top Chef......Sorry!!!! . This Flat is located in HISTORIC HARLEM.... near the Appollo Theater and The Museum Mile...on Fifth Avenue. Sylvia's World Famous Resturant...loca
description ||| WELCOME TO OUR INTERNATIONAL URBAN COMMUNITY This Spacious 1 bedroom  is with Plenty of Windows with a View....... Sleeps.....Four Adults.....two in the Livingrm. with (2) Sofa-beds.  (Website hidden by Airbnb) two in the Bedrm.on a very Comfortable Queen Size Bed... A Complete Bathrm.....With Shower and Bathtub....... Fully Equipped with Linens & Towels........ Spacious Living Room......Flat ScreenTelevision.....DVD Player with Movies available for your viewing during your stay............................................................................. Dining Area.....for Morning Coffee or Tea..................................................... The Kitchen Area is Modern with Granite Counter Top... includes the use of a Coffee Maker...Microwave to Heat up a Carry Out/In Meal.... Not suited for a Gourmet Cook...or Top Chef......Sorry!!!! . This Flat is located in HISTORIC HARLEM.... near the Appollo Theater and The Museum Mile...on Fifth Avenue. Sylvia's World Famous Resturant...loca
experiences_offered ||| none
neighborhood_overview ||| nan
notes ||| nan
transit ||| nan
access ||| nan
interaction ||| nan
house_rules ||| Upon arrival please have a legibile copy of your Passport  and / or State Photo. ID. as well as your confirmation letter. Please NO SMOKING ...LOUD TALKING or PARTIES of any kind. Security Deposit and Cleaning Fees in CASH at time of arrival. Security deposit will be refunded within 72hrs pending no damages. .Cleaning fees are non-refundable. At Check Out... Please dispose of all trash/garbage in the bins located outside behind the entrance stairs. Please place all dirty linens and towels in the dirty laundry bin. Please don't leave any dishes in the sink and dispose of all Plastic Dishes/Plastic Culinary. If you need a late check-out please contact the Emergency Contact Telephone Numbers that are listed in the Flat. PLEASE LEAVE ALL KEYS IN THE FLAT and BE CERTAIN THE DOORS ARE LOCKED. WE HOPE YOU ENJOYED YOUR STAY and will write positve comments and will visit again.
thumbnail_url ||| nan
medium_url ||| nan
picture_url ||| https://a0.muscache.com/im/pictures/838341/9b3c66f3_original.jpg?aki_policy=large
xl_picture_url ||| nan
host_id ||| 4632
host_url ||| https://www.airbnb.com/users/show/4632
host_name ||| Elisabeth
host_since ||| 2008-11-25
host_location ||| New York, New York, United States
host_about ||| Make Up Artist National/ (Website hidden by Airbnb) Production.
I m curently working with a Production Company in WDC and Coordinated a "Day Of Service " for the Presidential Innaugration 2013.
I can't live without Starbucks and Oprah's Chai Tea Latte...and my circle of  of  great friends world wide. "BLESS ME INTO USEFULLNESS" is my daily prayer.
I
host_response_time ||| a few days or more
host_response_rate ||| 0%
host_acceptance_rate ||| nan
host_is_superhost ||| f
host_thumbnail_url ||| https://a0.muscache.com/im/users/4632/profile_pic/1328402497/original.jpg?aki_policy=profile_small
host_picture_url ||| https://a0.muscache.com/im/users/4632/profile_pic/1328402497/original.jpg?aki_policy=profile_x_medium
host_neighbourhood ||| Harlem
host_listings_count ||| 1.0
host_total_listings_count ||| 1.0
host_verifications ||| ['email', 'phone', 'google', 'reviews', 'jumio', 'government_id']
host_has_profile_pic ||| t
host_identity_verified ||| t
street ||| New York, NY, United States
neighbourhood ||| Harlem
neighbourhood_cleansed ||| Harlem
neighbourhood_group_cleansed ||| Manhattan
city ||| New York
state ||| NY
zipcode ||| 10027
market ||| New York
smart_location ||| New York, NY
country_code ||| US
country ||| United States
latitude ||| 40.80902
longitude ||| -73.9419
is_location_exact ||| t
property_type ||| Apartment
room_type ||| Private room
accommodates ||| 2
bathrooms ||| 1.0
bedrooms ||| 1.0
beds ||| 1.0
bed_type ||| Pull-out Sofa
amenities ||| {"Cable TV",Internet,Wifi,"Air conditioning",Kitchen,"Buzzer/wireless intercom",Heating,"Smoke detector","Carbon monoxide detector","translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50"}
square_feet ||| nan
price ||| $150.00
weekly_price ||| nan
monthly_price ||| nan
security_deposit ||| $200.00
cleaning_fee ||| $75.00
guests_included ||| 2
extra_people ||| $20.00
minimum_nights ||| 3
maximum_nights ||| 7
minimum_minimum_nights ||| 3
maximum_minimum_nights ||| 3
minimum_maximum_nights ||| 7
maximum_maximum_nights ||| 7
minimum_nights_avg_ntm ||| 3.0
maximum_nights_avg_ntm ||| 7.0
calendar_updated ||| 37 months ago
has_availability ||| t
availability_30 ||| 30
availability_60 ||| 60
availability_90 ||| 90
availability_365 ||| 365
calendar_last_scraped ||| 2019-09-13
number_of_reviews ||| 0
number_of_reviews_ltm ||| 0
first_review ||| nan
last_review ||| nan
review_scores_rating ||| nan
review_scores_accuracy ||| nan
review_scores_cleanliness ||| nan
review_scores_checkin ||| nan
review_scores_communication ||| nan
review_scores_location ||| nan
review_scores_value ||| nan
requires_license ||| f
license ||| nan
jurisdiction_names ||| nan
instant_bookable ||| f
is_business_travel_ready ||| f
cancellation_policy ||| strict_14_with_grace_period
require_guest_profile_picture ||| t
require_guest_phone_verification ||| t
calculated_host_listings_count ||| 1
calculated_host_listings_count_entire_homes ||| 0
calculated_host_listings_count_private_rooms ||| 1
calculated_host_listings_count_shared_rooms ||| 0
reviews_per_month ||| nan

In [151]:
listings = listings[['neighbourhood_cleansed','neighbourhood_group_cleansed','city', 'state', 'zipcode', 'market','latitude', 'longitude','property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type','price', 'weekly_price', 'monthly_price','has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365']]

In [152]:
listings['room_type'].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'], dtype=object)

In [153]:
listings = listings[listings['room_type'] == 'Entire home/apt']

In [154]:
listings['bedrooms'].value_counts()

1.0     12406
2.0      5867
0.0      4018
3.0      1917
4.0       466
5.0       124
6.0        37
7.0        17
8.0         8
9.0         4
10.0        3
21.0        1
14.0        1
Name: bedrooms, dtype: int64

In [155]:
listings.loc[listings['bedrooms'] > 3,'bedrooms'] = 3

In [156]:
listings['bedrooms'].value_counts()

1.0    12406
2.0     5867
0.0     4018
3.0     2578
Name: bedrooms, dtype: int64

In [157]:
listings['price'] = listings['price'].apply(lambda x: float(x.strip('$').replace(',','')))

In [159]:
airbnb_all = listings.groupby(['neighbourhood_group_cleansed'])[['price']].agg(['median','count']).reset_index().rename(columns = {'neighbourhood_group_cleansed':'Borough'})

In [160]:
listings = listings.groupby(['neighbourhood_group_cleansed','bedrooms'])[['price']].agg(['median','count']).reset_index().rename(columns = {'neighbourhood_group_cleansed':'Borough'})

In [ ]:
airbnb_all.columns = [' '.join(col).strip() for col in airbnb_all.columns.values]
airbnb_all = airbnb_all.rename(columns = {'price median':'airbnb_price','price count':'airbnb_inventory'})

In [165]:
listings.columns = [' '.join(col).strip() for col in listings.columns.values]
listings = listings.rename(columns = {'price median':'airbnb_price','price count':'airbnb_inventory'})
listings

          Borough  bedrooms  airbnb_price  airbnb_inventory
0           Bronx       0.0          95.0                49
1           Bronx       1.0          90.0               195
2           Bronx       2.0         114.5                88
3           Bronx       3.0         190.0                59
4        Brooklyn       0.0         112.5               972
5        Brooklyn       1.0         125.0              4521
6        Brooklyn       2.0         160.0              2612
7        Brooklyn       3.0         250.0              1253
8       Manhattan       0.0         150.0              2727
9       Manhattan       1.0         180.0              6575
10      Manhattan       2.0         250.0              2628
11      Manhattan       3.0         400.0               879
12         Queens       0.0          96.0               249
13         Queens       1.0         100.0              1049
14         Queens       2.0         140.0               494
15         Queens       3.0         200.0               340
16  Staten Island       0.0          70.0                21
17  Staten Island       1.0          89.5                66
18  Staten Island       2.0         100.0                45
19  Staten Island       3.0         180.0                47

In [168]:
listings.loc[:,'bedrooms'] = listings['bedrooms'].map({0:'Studio',1:'OneBd',2:'TwoBd',3:'ThreePlusBd'})

In [171]:
airbnb_all['bedrooms'] = 'All'

         Borough  airbnb_price  airbnb_inventory bedrooms
0          Bronx         100.0               392      All
1       Brooklyn         145.0              9364      All
2      Manhattan         194.0             12828      All
3         Queens         120.0              2135      All
4  Staten Island         100.0               179      All

In [174]:
airbnb = pd.concat([airbnb_all,listings])
airbnb

          Borough  airbnb_inventory  airbnb_price     bedrooms
0           Bronx               392         100.0          All
1        Brooklyn              9364         145.0          All
2       Manhattan             12828         194.0          All
3          Queens              2135         120.0          All
4   Staten Island               179         100.0          All
0           Bronx                49          95.0       Studio
1           Bronx               195          90.0        OneBd
2           Bronx                88         114.5        TwoBd
3           Bronx                59         190.0  ThreePlusBd
4        Brooklyn               972         112.5       Studio
5        Brooklyn              4521         125.0        OneBd
6        Brooklyn              2612         160.0        TwoBd
7        Brooklyn              1253         250.0  ThreePlusBd
8       Manhattan              2727         150.0       Studio
9       Manhattan              6575         180.0        OneBd
10      Manhattan              2628         250.0        TwoBd
11      Manhattan               879         400.0  ThreePlusBd
12         Queens               249          96.0       Studio
13         Queens              1049         100.0        OneBd
14         Queens               494         140.0        TwoBd
15         Queens               340         200.0  ThreePlusBd
16  Staten Island                21          70.0       Studio
17  Staten Island                66          89.5        OneBd
18  Staten Island                45         100.0        TwoBd
19  Staten Island                47         180.0  ThreePlusBd

In [133]:
price = pd.melt(price, id_vars=['Borough'], value_vars=['All', 'Studio','OneBd','TwoBd','ThreePlusBd']).rename(columns = {'variable':'type','value':'price'})
inventory = pd.melt(inventory, id_vars=['Borough'], value_vars=['All', 'Studio','OneBd','TwoBd','ThreePlusBd']).rename(columns = {'variable':'type','value':'inventory'})

         Borough type   price  inventory
0          Bronx  All  1900.0     1154.0
1       Brooklyn  All  2550.0    17556.0
2      Manhattan  All  3300.0    19604.0
3         Queens  All  2200.0     5581.0
4  Staten Island  All  1900.0       97.0

In [147]:
rental = price.merge(inventory,on = ['Borough','type'])

In [176]:
host = rental.merge(airbnb, left_on = ['Borough','type'], right_on=['Borough','bedrooms'])

In [183]:
host = host.drop(['bedrooms'], axis = 1).rename(columns = {'price':'rental_price','inventory':'rental_inventory'})

In [184]:
host.to_csv('../data/host.csv')